name: Feature Request
description: Request a new feature
labels: [bug, triage]

body:
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like?
      description: A clear and concise description about the feature what you want have.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is, e.g. I'm always frustrated when [...].

  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: A clear and concise description of any alternative solutions or features you've considered.


  - type: textarea
    id: additional
    attributes:
      label: Do you have any additional context?
      description: Add any other context or screenshots about the feature request here.
