name: New issue
description: Do not find right premade form to open your github issue? No problem you can just  open a regular issue.
labels: [triage]

body:
  - type: input
    id: summary
    attributes:
      label: Issue summary
      description: Short summary about the issue.
      placeholder: ex. This should be enhanced...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue, what this issue covers.
      placeholder: Tell us more!
    validations:
      required: false

  - type: textarea
    id: logs-code
    attributes:
      label: Aditional context
      description: Provide aditional context if needed like aditional resources, links etc.

  - type: dropdown
    id: terms
    attributes:
      label: '-'
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/howijd/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - I agree to follow this project's Code of Conduct
    validations:
      required: true


