name: maintainers - (task) template
description: (Maintainers Only!) Form to draft new howijd.network task.
title: "e.g. Fix bug, enhance, implement feature x"
labels:
  - dao/task
  - draft
# assignees:
#   - howijd/maintainers

body:
  - type: markdown
    attributes:
      value: |
        NOTE! This is form for maintainers and will be automatically closed if opened by user not belonging to **@howijd/maintainers** team.

  - id: acceptance
    type: input
    attributes:
      label: Acceptance
      description: Task primary objective or acceptance criteria.
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: The Abstract
      placeholder: Abstracts are important because they give a first impression of the milestone!
    validations:
      required: true

  - type: textarea
    id: hntasks
    attributes:
      label: Tasks
      description: List of tasks.
      value: |
        - [ ] ... # e.g howiijd/howiijd.org#x
    validations:
      required: false

  - type: textarea
    id: resource-links
    attributes:
      label: Resources
      description: Relevant resources and links.
      value: |
        | resources | description |
        | --- | --- |
        | ... | ... |
    validations:
      required: false

  - type: markdown
    attributes:
      value: list this task also under correct milestone or story
