name: maintainers - (era) template
description: (Maintainers Only!) Form to draft new howijd.network era.
title: "e.g. Okram era"
labels:
  - dao/era
  - draft

# assignees:
#   - howijd/maintainers

body:
  - type: markdown
    attributes:
      value: |
        NOTE! This is form for maintainers and will be automatically closed if opened by user not belonging to **@howijd/maintainers** team.

  - id: slogan
    type: input
    attributes:
      label: Slogan or tagline
      description: short description or slogan for this era.
      placeholder: '# ...'
    validations:
      required: true

  - id: semver
    type: input
    attributes:
      label: Version
      description: Semantic version for this era.
      placeholder: '1.0.0'
    validations:
      required: true

  - id: lock-date
    type: input
    attributes:
      label: 'Start:'
      description: Start date or when era API definitions and features will be soft locked.
      placeholder: 'dd.mm.yyyy || TBD'
    validations:
      required: true

  - type: input
    id: release-date
    attributes:
      label: 'Release date:'
      description: Estimated release date.
      placeholder: 'dd.mm.yyyy || TBD'
    validations:
      required: true

  - type: input
    id: era-discussion-link
    attributes:
      label: 'Discussions:'
      description: Community discussions around this era.
      placeholder: 'link to discussion category'
    validations:
      required: true

  - type: input
    id: prevous-era-link
    attributes:
      label: 'Previous era:'
      placeholder: 'howijd.network/roadmap/era/...'
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: The Abstract
      placeholder: Abstracts are important because they give a first impression of the era!
    validations:
      required: true

  - type: textarea
    id: hnmiles
    attributes:
      label: Milestones
      description: List of related milestones under this era.
      value: |
        - [ ] ... # e.g howiijd/howiijd.org#x
    validations:
      required: true

  - type: textarea
    id: resource-links
    attributes:
      label: Resources
      description: Relevant resources and links.
      value: |
        | resources | description |
        | --- | --- |
        | ... | ... |
    validations:
      required: true
