name: New task
description: Do not find right premade form to open your github issue? No problem you can just  open a regular task.
labels: [triage]

body:
  - type: input
    id: summary
    attributes:
      label: Task summary
      description: Short summary about the task.
      placeholder: ex. This should be enhanced...
    validations:
      required: true

  - type: markdown
    id: description
    attributes:
      label: Description
      description: Describe the task, what should this task cover.
      placeholder: Tell us more!
    validations:
      required: true

  - type: markdown
    id: logs-code
    attributes:
      label: Aditional context
      description: Provide aditional context if needed like aditional resources, links etc.

  - type: dropdown
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/howijd/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - I agree to follow this project's Code of Conduct
      validations:
        required: true


