name: Manage labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/manage-labels.yml'
      - 'labels.yml'


jobs:
  manage-labels:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'howijd/.github'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/label-manager
        with:
          token: ${{ secrets.HOWIBOT_GITHUB_TOKEN }}
