name: Manage labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/manage-labels.yml'
      - '.github/actions/update-workflow-files/action.yml'


jobs:
  manage-your-labels:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'howijd/.github'
    steps:
      - name: manage-your-labels
        uses: actions-automation/manage-your-labels@0.1.0
