name: Manage labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/manage-labels.yml'
      - 'manage-your-labels.yml'


jobs:
  manage-your-labels:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'howijd/.github'
    steps:
      - uses: .github/actions/label-manager
        with:
          token: ${{ secrets.HOWIBOT_GITHUB_TOKEN }}
