name: Update Workflow files

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-workflow-files.yml'
      - '.github/actions/update-workflow-files/action.yml'
      - 'workflow-templates/**.yml'


jobs:
  open-pullrequests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'howijd/.github'
    strategy:
      matrix:
        repo:
          - howijd/howijd.network
          # - howijd/howijd.org
          # - howijd/howijd.com
          - howijd/howi
    name: ${{ matrix.repo }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: src
      - uses: ./src/.github/actions/update-workflow-files
        with:
          repository: ${{ matrix.repo }}
          ref: main
          token: ${{ secrets.HOWIBOT_GITHUB_TOKEN }}
