name: Update Workflow files

on:
  # RUNS ONLY IN .github REPO TO DISPATCH FOR OTHER REPOS
  push:
    paths:
      - '.github/workflows/update-workflow-files.yml'
      - 'workflow-templates/**.yml'
  # / RUNS ONLY IN .github REPO TO DISPATCH FOR OTHER REPOS

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: echo "${{ toJSON(github) }}"

  # update:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: wget -N -P .github/workflows https://raw.githubusercontent.com/howijd/.github/main/workflow-templates/github-issues.yml
  #     - uses: peter-evans/create-pull-request@v3.10.1
  #       with:
  #         token: ${{ secrets.HOWIBOT_GITHUB_TOKEN }}
  #         commit-message: 'update github-issues.yml based on upstream'
  #         signoff: true
  #         branch: patch/github-issues.yml
  #         delete-branch: true
  #         committer: HOWI BOT <howi@howijd.network>
  #         base: main
  #         title: update github-issues.yml based on upstream
  #         body: |
  #           **NOTICE!**

  #           This Workflow file is tested with [this workflow](https://github.com/howijd/.github/blob/main/.github/workflows/github-issues.yml)
  #           And based on this [workflow file](https://github.com/howijd/.github/blob/main/workflow-templates/github-issues.yml)
  #         labels: enhancement


  # # SHOULD RUN ONLY IN .github REPO TO DISPATCH FOR OTHER REPOS
  # dipatch-update:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.repository == 'howijd/.github'
  #   strategy:
  #     matrix:
  #       repo:
  #         - howijd/howijd.network
  #         - howijd/howijd.org
  #         - howijd/howijd.com
  #         - howijd/howi
  #   steps:
  #     - uses: peter-evans/repository-dispatch@v1
  #       with:
  #         token: ${{ secrets.HOWIBOT_GITHUB_TOKEN }}
  #         repository: ${{ matrix.repo }}
  #         event-type: workflow-file-github-issues
